* Languages
** Used in production:
- Ruby
- Javascript (and dialects: Coffeescript, Typescript, Ecmascript 6)
- Elixir
- Golang
- Python
- Chef
- Ansible
- Terraform
** Wrote projects in:
- Clojure and Clojurescript
- SaltStack
- C++11
- Rust
- Haskell
- C
- C# and F#
- Prolog
- Ocaml / SML
* OS
** Linux
*** Arch, Antergos
Used as my workstation system during studies and early years of work (2012-2016).
*** Ubuntu, Debian
Primary OS of choice for VPS and administrated machines (went through updates from 12.04 to 16.04).
*** Alpine
Primary choice for Docker images.
*** CoreOS
Experimented a little with, for setting up containerised services.
** macOS
Switched from Linux in 2016, still not sure if it was a good choice.
* Work experience
** Tooploox (2015--now)
*** Golem app
Remote camera control for iOS devices. Wrote:
- Node.js server (Coffeescript app with REST API in Express and realtime communication via socket.io, backed by Redis and MongoDB),
- Web app (Javascript SPA with React and socket.io),
- Admin panel (Javascript SPA with Angular 1.0 and socket.io).
*** MedMapr
Tracking location of medical equipment with Estimote beacons. Worked on tracking devices - Linux on Android Mini PC sticks.
*** NowThis
*** Group Nine Media
*** Internal projects (To be announced)
* Education
** Master of Computer Science
2011-2016
Computer Science Institute, The University of Wroclaw
** XIVLO
2008-2011
Bilingual class with emphasis on mathematics and physics
* Achievements
** Prexy scholarship
2012-2014
Awarded to students with grade average over 4.5 (about 5\% of students).
** Comissioned Studies Scholarship
2011-2014
Awarded to better 50\% of students. Consecutively awarded since beginning of studies.
** Matura exam
2011
Scored over 95\% in mathematics (basic and extended level), over 80\% score in english.
** SAT exam
2010
Scored over 90\% in mathematics (both high school and academic level) and physics, over 80\% average score in english.
* Academic and personal projects
** Algorithms and Data Structures, University of Wroclaw
2013
Various small but interesting algorithms (e.g. BFS, AStar, Heap, AVLTrees, UnionFind).
** Earth simulation in new OpenGL/C++
2012
Course: Introduction to Computer Science course, University of Wroclaw.
Medium size project using modern OpenGL to render simulation akin to Google Earth.
** RPG Game in PyGame
2012
Course: Interactive applications in Python course, University of Wroclaw.
Team project of writing a game, complete with particle effects, AI and sound.
* Interests
** Professional
- Networking
- Machine learning and numerical analysis
- Computer graphics / game development
- Formal semantics of programming languages
** Personal
- Windsurfing
- Yachting
- Tabletop and collectible card games
