* Experience
** Tooploox
    :FROM: 2014-06-07
    :TO: 2019-10-31
    :POSITION: Fullstack Developer
    Joined as a Junior, left on a path to Seniority after 5 years. In the meantime built products with many startups and startup-like companies (listed underneath). Had the chance to take part in explosive growth of the organisation (from 6 to over 150 people).
** One of major car manufacturers
    :FROM: 2019-09-01
    :TO: 2019-10-31
    :POSITION: Freelance Researcher / Developer
    Proof-of-concept for API working in car's head unit, providing information about broadcasts based on car location.
    Designed update & storage mechanism,
    Implemented set of embedded binaries with Go,
    Cleaned production data & simulated patching process throughout a year,
** Quizzpy
    :ICON: https://d33wubrfki0l68.cloudfront.net/b0e95300f043b4d28372f8cf19277df987c936bc/b2032/quizzpy-logo.2aacc600.svg
    :FROM: 2018-03-01
    :TO: 2019-09-01
    :POSITION: Tech Lead / Principle Software Engineer
    Live trivia show, targeted for Polish audience. Worked in small cross-competence Scrum team.
    Spearheaded architecture & scaling efforts,
    Took part in implementation of backend in Elixir,
    Supported streaming pipeline while reducing infrastructure costs,
    Converted infrastructure into IaaC model & maintained it using Ansible & Terraform,
    Evaluated several Kanban boards to be used by development team (Trello, Taiga, Zenhub),
** Implementation of Holacracy
    :ICON: https://images.squarespace-cdn.com/content/5d1239a79c02150001db74d4/1561475648342-TU0F0W6TRID5IAKCKM0E/Holacracy_Primary.png?format=1500w&content-type=image%2Fpng
    :FROM: 2018-09-01
    :TO: 2019-10-31
    :POSITION: Various roles
    Part of initial group which evaluated various frameworks for power division in organisation.
    Shared knowledge about Holacracy as one of initial mentors,
    Spearheaded forming structures around Engineering group as Facilitator, Architect, Estimator and later Strategy Guardian,
** Group Nine Media
    :ICON: https://en.wikipedia.org/wiki/Group_Nine_Media#/media/File:Group_Nine_Media_Logo.svg
    :FROM: 2016-01-01
    :TO: 2018-03-01
    :POSITION: Data Pipeline Tech Lead
    Platform for monitoring & analysis of publishings on social platforms.
    Took over PoCs created by AI/ML Engineers, mostly working with CSVs,
    Designed initial push into online system based on Lambda architecture,
    Lead team of engineers which implemented whole pipeline,
    Maintained features for users like Anomaly Detection and Looker integration,
    Helped Data Scientists work with over 3TB of data with PySpark, Jupyter and Apache Zeppelin,
    Took part in on-call system which helped keep the system online for 2 years,
    Implemented and oversaw monitoring using Datadog,
    Helped Ops team maintain and extend infrastructure with Chef,
** NowThis
    :ICON: https://en.wikipedia.org/wiki/NowThis_News#/media/File:Now_This_Logo_White.svg
    :FROM: 2014-10-01
    :TO: 2016-01-01
    :POSITION: Backend Developer
    Custom workflow & automatization platform. Worked part-time as part of several backend groups.
    Helped design architecture based on EventSourcing and CQRS,
    Implemented CI/CD pipeline using Ruby and Jenkins,
    Helped developers deploy and debug containers using Docker, Hashicorp Nomad & Vault,
** Golem app
    :ICON: https://web.archive.org/web/20160318141954im_/http://golemapp.com/static/images/logo.png
    :FROM: 2014-06-07
    :TO: 2014-09-01
    :POSITION: Junior Fullstack Developer
    Remote camera control for iOS devices with Galileo.
    Wrote simple backend in Node.js,
    Implemented analytics features using MongoDB and Angular 1.0,
    Added Hangouts integration with React,
    Took care of deployment and maintenance with Fabric on Debian,
* Skills
** Backend
   :LEVEL: Senior
    Golang / Elixir / Ruby / Node.js
    Postgres / Redis / Cassandra
** Ops
   :LEVEL: Senior
    Chef / Ansible / Terraform
    GCP / AWS / OVH
    CDNs
    Docker / Kubernetes
** Frontend
   :LEVEL: Mid
    Javascript
    Css / Sass
    React / Redux / Vue.js
** Architecture
   :LEVEL: Mid
    Event Sourcing / CQRS / DDD
    Lambda architecture
** Big Data
   :LEVEL: Mid
    Python (Pandas / PySpark)
    BigQuery
** Product development
   :LEVEL: Mid
    Agile methodology / Lean / Scrum
    Github / Zenhub / Jira / Confluence
* Education
** Master of Computer Science (2011-2016)
   :FROM: 2011-10-01
   :TO: 2016-11-07
   :DEGREE: Masters
   :INSTITUTION: University of Wroclaw
   :AREA: Computer Science
  Computer Science Institute, University of Wroclaw
* Basics
  :NAME: Łukasz Czapliński
  :LABEL: Web Developer / Architect
  :EMAIL: lukasz@czaplin.ski
  :SUMMARY: I'm a fullstack with focus on delivering & evolving products, not simply building features according to schedule. I'm open to working both remotely and on-site.
** Location
   :CITY: Wrocław
   :COUNTRY: PL
** Profiles
*** Github
    :USERNAME: scoiatael
    :URL: https://github.com/scoiatael
*** Keybase
    :USERNAME: scoiatael
    :URL: https://keybase.io/scoiatael
* Interests
** Yachting
    Polish skipper degree
** Tabletop and collectible card games
    Magic the Gathering
    Warhammer 40k
** Windsurfing
* Languages
** Polish
    :LEVEL: native
** English
    :LEVEL: bilingual
