on:
  push:
    branches:
    - master

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Build project
        id: build_resume_json
        run: |
          lein build-resume-json
          lein build-resume-html
          echo "##[set-output name=version;]$(cat project.clj | head -n 1 | awk '{ print $3 }' | tr -d '\"')"

      - name: Tag Release
        run: |
          git tag v${{ steps.build_resume_json.outputs.version }}
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.build_resume_json.outputs.version }}
          release_name: v${{ steps.build_resume_json.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload resume.json
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/resume.json
          asset_name: resume.json
          asset_content_type: application/json

      - name: Upload resume.html
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/dist/resume.html
          asset_name: resume.html
          asset_content_type: text/html
